// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearResume() {
  return window['go']['main']['App']['ClearResume']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function RunRepairPhase(arg1) {
  return window['go']['main']['App']['RunRepairPhase'](arg1);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function ScheduleResume() {
  return window['go']['main']['App']['ScheduleResume']();
}

export function StopRepair() {
  return window['go']['main']['App']['StopRepair']();
}

export function GetApplications() {
  return window['go']['main']['App']['GetApplications']();
}
