// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sysinfo} from '../models';

export function ClearResume():Promise<string>;

export function GetSystemInfo():Promise<sysinfo.Info>;

export function Greet(arg1:string):Promise<string>;

export function LoadState():Promise<number>;

export function RunCommand(arg1:string):Promise<string>;

export function RunRepairPhase(arg1:number):Promise<string>;

export function SaveState(arg1:number):Promise<void>;

export function ScheduleResume():Promise<string>;

export function StopRepair():Promise<void>;
